version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    # php:
    #     image: php:fpm
    #     command: docker-php-ext-install pdo pdo_mysql
    #     volumes:
    #         - ./code:/code
    #         - ./php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    php:
        build: ./php
        volumes:
            - ./code:/code
            - ./php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    mysql:
        image: mysql:5.7
    #    command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080